name: deploy-app-container-azure

on:
  push:
    branches:
      - az
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: upload to blob storage
        uses: azure/cli@v1
        with:
          inlinescript: |
              az storage blob upload-batch --account-name ${{ secrets.storage_account_name }} --auth-mode key -d '$web' -s $GITHUB_WORKSPACE/packages/container/dist
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{ secrets.CDN_PROFILE_NAME }} --name ${{ secrets.CDN_ENDPOINT }} --resource-group ${{ secrets.RESOURCE_GROUP }}

      # Azure logout
      - name: logout
        run: |
              az logout
        if: always()